# Generated by Django 5.2.11 on 2026-03-01 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('passenger_id_number', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('ticket_sent', models.BooleanField(default=False)),
                ('created_by_driver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatutuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_capacity', models.PositiveIntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MTN Sacco', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='booking_app.sacco')),
            ],
        ),
        migrations.CreateModel(
            name='MatutuOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='booking_app.sacco')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_number', models.CharField(max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200)),
                ('merchant_request_id', models.CharField(blank=True, max_length=200)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='initiated', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Matatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('stage', 'Stage (Fill & Go)'), ('express', 'Express (Scheduled Trips)')], default='stage', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matatus', to='booking_app.driver')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matatus', to='booking_app.matutuowner')),
                ('matatu_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matatus', to='booking_app.matututype')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matatus', to='booking_app.route')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matatus', to='booking_app.sacco')),
            ],
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(choices=[('window', 'Window'), ('aisle', 'Aisle'), ('front', 'Front Passenger'), ('conductor', 'Conductor')], default='window', max_length=20)),
                ('row_number', models.PositiveIntegerField()),
                ('column_number', models.PositiveIntegerField()),
                ('row_span', models.PositiveIntegerField(default=1)),
                ('col_span', models.PositiveIntegerField(default=1)),
                ('is_aisle_gap', models.BooleanField(default=False)),
                ('is_driver_seat', models.BooleanField(default=False)),
                ('is_conductor_seat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bg_color', models.CharField(blank=True, default='', max_length=20)),
                ('text_color', models.CharField(blank=True, default='', max_length=20)),
                ('custom_label', models.CharField(blank=True, default='', max_length=20)),
                ('extra_padding', models.PositiveIntegerField(default=0)),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking_app.matatu')),
            ],
            options={
                'ordering': ['row_number', 'column_number'],
                'unique_together': {('matatu', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='alighting_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alighting_bookings', to='booking_app.stage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='boarding_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_bookings', to='booking_app.stage'),
        ),
        migrations.CreateModel(
            name='StageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='loading', max_length=20)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_stage_runs', to='booking_app.stage')),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_runs', to='booking_app.matatu')),
                ('origin_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_runs', to='booking_app.stage')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_runs', to='booking_app.route')),
            ],
            options={
                'ordering': ['-run_date', '-run_number'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='stage_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.stagerun'),
        ),
        migrations.AddField(
            model_name='stage',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='booking_app.town'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='booking_app.town'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='booking_app.town'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_trips', to='booking_app.stage')),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking_app.matatu')),
                ('origin_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_trips', to='booking_app.stage')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking_app.route')),
            ],
            options={
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.trip'),
        ),
        migrations.CreateModel(
            name='DailyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.driver')),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_earnings', to='booking_app.matatu')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('matatu', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='booking_app.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.seatlayout')),
            ],
            options={
                'unique_together': {('booking', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('distance_from_origin_km', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='booking_app.route')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.stage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'stage')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('town', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination')},
        ),
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='booking_app.seatlayout')),
                ('stage_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='booking_app.stagerun')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='booking_app.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='booking_app_expires_6da088_idx')],
            },
        ),
    ]
